feat: script to generate report
open-craft/cross-section-link-report pull request #1
Opened 2023-05-12 18:36 UTC by kaustavb12

## Description

Script to generate report about the prevelance of cross-sectional report

## Testing instructions

Check the [README](https://github.com/open-craft/cross-section-link-report/blob/kaustav/generate_report_script/README.md)

## Other information

OpenCraft internal ticket : BB-7352

2023-05-12 19:51 UTC, Kelketek commented
@kaustavb12 This is working for me. Please add in the counters for the other items Piotr mentioned. The only concern I have right now is if the authentication will work on the client's production instance since they have SSO, but I'm pretty sure it will, since I think the kind of authentication you're doing bypasses that. However I don't have an account to verify that with.

2023-05-15 12:33 UTC, Agrendalath requested changes
@kaustavb12, I started testing this on Stage, and the first course (with 925 blocks) took 6 minutes to process. The CPU usage of the remote instance was ~50%. If other courses have similar sizes, it will take more than 11h to process this (assuming that we wouldn't run out of memory or file descriptors (described in the next paragraph).

I wanted to speed things up, so I changed the `REQUEST_BATCH_SIZE` to 100. It took 4 minutes to process the first course. The CPU usage of the remote instance was ~70%. However, while retrieving the blocks for the second course, I got `OSError: [Errno 24] Too many open files`. That's odd, as I set the limit for open file descriptors to `1024`. Maybe `grequests` is not closing the connections properly?

In any case, the API views are too inefficient for such a heavy operation. We may want to get the data from the `modulestore` directly instead. It's OK to run this script directly on Stage - it does not need to be a full Django app (or even a Python package) - see the scripts I linked in the Jira ticket for an example of how this could look like.

cc: @Kelketek

2023-05-15 12:33 UTC, Agrendalath commented on README.md
> +1. Create a new file called `config.yml` based on `confiy.yml.example`. Populate all the variables there.
```suggestion
1. Create a new file called `config.yml` based on `config.yml.example`. Populate all the variables there.
```

2023-05-15 12:33 UTC, Agrendalath commented on README.md
> +pip install -r requirement.txt
Nit: let's rename `requirement.txt` to `requirements.txt`.

2023-05-15 12:33 UTC, Agrendalath commented on config.yml.example
> +REPORT_PATH: /home/reports/output
We could just hardcode this to `/tmp/cross-section-link-report.html`.

2023-05-15 12:33 UTC, Agrendalath commented on generate_report.py
> +cookie_jar = login.login_to_lms()
```suggestion
session = login.login_to_lms()
```

Nit: it seems to be more self-explanatory.

2023-05-15 12:33 UTC, Agrendalath commented on generate_report.py
> +for course in active_courses:
```suggestion
for course_number, course in enumerate(active_courses, start=1):
```

2023-05-15 12:33 UTC, Agrendalath commented on generate_report.py
> +    print(f"Course {course_count}/{len(active_courses)} : Fetching all blocks of course {course}")
```suggestion
    print(f"Course {course_count}/{len(active_courses)} : Fetching all blocks for course {course}")
```

2023-05-15 12:33 UTC, Agrendalath commented on generate_report.py
> +generate_report(active_courses)
```suggestion
if __name__ == "__main__":
    generate_report(active_courses)
```

Nit: we don't want to run this if this file is imported (for any reason).

2023-05-15 12:33 UTC, Agrendalath commented on generate_report.py
> +    print(f"Course {course_count}/{len(active_courses)} : Fetching all blocks of course {course}")
Could we use `log.info`? It gives additional helpful information (e.g., the timestamp and code location).

2023-05-15 12:33 UTC, Agrendalath commented on helpers/helper.py
> +    reqs = [grequests.get(FETCH_ALL_COURSES_URL, cookies=cookie_jar)]
This API retrieves only some courses for me in the Stage environment (as a superuser). I expanded the `FETCH_ALL_COURSES_URL` URL with `?page_size=100` ([max value](https://github.com/openedx/edx-platform/blob/6adf45df2f25a0e44d08047b6b36997cab51b99c/lms/djangoapps/course_api/views.py#L317)) and got 16 results from this method.

## Comparison
### This script
```python
In [1]: from helpers.login import login_to_lms
In [2]: from helpers.helper import fetch_all_active_courses
In [3]: session = login_to_lms()
Fetching session cookies for login
Logging in using staff credentials
In [4]: courses = fetch_all_active_courses(session)
Fetching list of all courses
In [5]: len(courses)
Out[5]: 16
```

### Django shell
```python
In [1]: import pytz
In [2]: from datetime import datetime
In [3]: from django.db.models import Q
In [4]: from openedx.core.djangoapps.content.course_overviews.models import CourseOverview
In [5]: CourseOverview.objects.filter(Q(end=None) | Q(end__gt=datetime.now(tz=pytz.UTC))).count()
Out[5]: 114
```

# Update

I modified the current script to something like this (see comments in the code):
```python
# This is important - if the `username` is not specified, the user is treated as an anonymous one.
FETCH_ALL_COURSES_URL = f"{LMS_URL}/api/courses/v1/courses/?page_size=100&username=Piotr"

def fetch_all_active_courses(cookie_jar):
    '''
    Fetch list of all courses.
    Discards courses whose end date is defined and is in the past.
    Returns the other courses as active courses.
    '''
    active_courses = []

    # This API is paginated.
    next_page = FETCH_ALL_COURSES_URL
    while next_page:
        print("Fetching list of all courses")
        reqs = [grequests.get(next_page, cookies=cookie_jar)]
        r = grequests.map(reqs)[0]

        courses = r.json().get('results')
        today = datetime.now()
        for course in courses:
            course_active = False
            end_date_str = course.get('end', None)
            if end_date_str:
                end_date_str = end_date_str.split('T')[0]
                end_date = datetime.strptime(end_date_str, '%Y-%m-%d')
                if end_date >= today:
                    course_active = True
            else:
                course_active = True

            if course_active:
                course = Course(course)
                course.url = f"{STUDIO_URL}/course/{course.id}"
                active_courses.append(course)
        next_page = r.json().get('pagination').get('next')

    return active_courses
```

This returns 112 courses. I compared the outputs, and the discrepancy comes from the Sites (this environment has a second Site with courses filtered by an organization). In this case, it's safe to ignore.

2023-05-15 12:33 UTC, Agrendalath commented on helpers/helper.py
> +            course_active = True
Life's too short to parse dates manually. Just install [python-dateutil](https://pypi.org/project/python-dateutil/), import `from dateutil.parser import parse`, and do something like:
```suggestion
        try:
            course_active = parse(end_date, ignoretz=True) >= today:
        except TypeError:
            # End date is undefined.
            course_active = True
```

2023-05-15 12:33 UTC, Agrendalath commented on helpers/helper.py
> +    grequests.map(reqs, size=REQUEST_BATCH_SIZE)
Does the [component_handler](https://github.com/openedx/edx-platform/blob/2f9c61e29a941545bd0216a76812c1270c5e871e/cms/djangoapps/contentstore/views/component.py#L491-L535) have rate limiting?

2023-05-15 12:33 UTC, Agrendalath commented on helpers/classes.py
> +    def __str__(self) -> str:
```suggestion
    def __repr__(self) -> str:
```

This will also work for debugging.

2023-05-15 12:33 UTC, Agrendalath commented on helpers/classes.py
> +    def __str__(self) -> str:
```suggestion
    def __repr__(self) -> str:
```

This will also work for debugging.

2023-06-15 12:30 UTC, closed without merging